// Centralized Mock Data for Royaltraditionalcraft
// This file ensures consistency between shop, detail, and recommendations.

export const MOCK_CATEGORIES = [
  { id: "cat_sofas", name: "Luxury Sofa Sets", slug: "sofas" },
  { id: "cat_beds", name: "Premium Bedframes", slug: "beds" },
  { id: "cat_tables", name: "Elegant Dining & Coffee Tables", slug: "tables" },
  { id: "cat_chairs", name: "Designer Chairs", slug: "chairs" },
  { id: "cat_vanity", name: "Vanity & Dressing Units", slug: "vanity" },
  { id: "cat_wardrobes", name: "Wardrobe & Storage Solutions", slug: "wardrobes" },
  { id: "cat_media", name: "Media & TV Consoles", slug: "media" },
  { id: "cat_mattress", name: "Orthopedic & Comfort Mattresses", slug: "mattress" },
  { id: "cat_bookshelves", name: "Modern Bookshelves & Racks", slug: "bookshelves" },
  { id: "cat_executive", name: "Executive & Occasional Seating", slug: "executive" },
  { id: "cat_prayer", name: "Divine Prayer Units", slug: "prayer" },
];

export const MOCK_PRODUCTS = [
  { 
    id: "p1", 
    name: "Maharaja King Bed", 
    slug: "maharaja-king-bed", 
    price: 89999, 
    description: "Our flagship king-size bed, handcrafted from premium Sheesham wood with intricate carvings. Includes a velvet-tufted headboard.",
    stock: 5, 
    categoryId: "cat_beds",
    category: { name: "Premium Bedframes", slug: "beds" }, 
    images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=800"], 
    tags: ["premium", "royal", "wood", "bedroom"],
    reviews: [],
    _count: { reviews: 15 }, 
    isActive: true, 
    createdAt: "2024-01-01T00:00:00.000Z" 
  },
  { 
    id: "p2", 
    name: "Royal Sheesham Dining Table", 
    slug: "royal-dining-table", 
    price: 65000, 
    description: "A grand 6-seater dining table made of solid Sheesham. Perfect for royal family gatherings.",
    stock: 3, 
    categoryId: "cat_tables",
    category: { name: "Elegant Dining & Coffee Tables", slug: "tables" }, 
    images: ["https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?q=80&w=800"], 
    tags: ["dining", "wood", "royal", "sheesham"],
    reviews: [],
    _count: { reviews: 8 }, 
    isActive: true, 
    createdAt: "2024-01-02T00:00:00.000Z" 
  },
  { 
    id: "p3", 
    name: "Velvet Chesterfield Sofa", 
    slug: "chesterfield-sofa", 
    price: 45000, 
    description: "Classic Chesterfield design with deep buttoning and rich velvet upholstery.",
    stock: 10, 
    categoryId: "cat_sofas",
    category: { name: "Luxury Sofa Sets", slug: "sofas" }, 
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800"], 
    tags: ["living", "sofa", "velvet", "classic"],
    reviews: [],
    _count: { reviews: 12 }, 
    isActive: true, 
    createdAt: "2024-01-03T00:00:00.000Z" 
  },
  { 
    id: "p4", 
    name: "Teak Armchair", 
    slug: "teak-armchair", 
    price: 18500, 
    description: "Elegant teak wood armchair with traditional carvings and comfortable seating.",
    stock: 15, 
    categoryId: "cat_chairs",
    category: { name: "Designer Chairs", slug: "chairs" }, 
    images: ["https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800"], 
    tags: ["seating", "wood", "accent", "teak"],
    reviews: [],
    _count: { reviews: 20 }, 
    isActive: true, 
    createdAt: "2024-01-04T00:00:00.000Z" 
  },
  { 
    id: "p5", 
    name: "Traditional 3-Door Wardrobe", 
    slug: "traditional-wardrobe", 
    price: 75000, 
    description: "Spacious wardrobes with handcarved panels and premium finish.",
    stock: 2, 
    categoryId: "cat_wardrobes",
    category: { name: "Wardrobe & Storage Solutions", slug: "wardrobes" }, 
    images: ["https://images.unsplash.com/photo-1595428774223-ef52624120d2?q=80&w=800"], 
    tags: ["storage", "bedroom", "wood", "luxury"],
    reviews: [],
    _count: { reviews: 5 }, 
    isActive: true, 
    createdAt: "2024-01-05T00:00:00.000Z" 
  },
  { 
    id: "p6", 
    name: "Sheesham Bookshelf", 
    slug: "sheesham-bookshelf", 
    price: 28000, 
    description: "Solid wood bookshelf featuring multiple tiers for your royal library.",
    stock: 8, 
    categoryId: "cat_bookshelves",
    category: { name: "Modern Bookshelves & Racks", slug: "bookshelves" }, 
    images: ["https://images.unsplash.com/photo-1594620302200-9a762244a156?q=80&w=800"], 
    tags: ["library", "storage", "wood", "office"],
    reviews: [],
    _count: { reviews: 10 }, 
    isActive: true, 
    createdAt: "2024-01-06T00:00:00.000Z" 
  },
  { 
    id: "p7", 
    name: "Queen Size Poster Bed", 
    slug: "queen-poster-bed", 
    price: 72000, 
    description: "A beautifully elegant queen size poster bed with a refined aesthetic.",
    stock: 4, 
    categoryId: "cat_beds",
    category: { name: "Premium Bedframes", slug: "beds" }, 
    images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=800"], 
    tags: ["poster-bed", "bedroom", "premium", "queen"],
    reviews: [],
    _count: { reviews: 18 }, 
    isActive: true, 
    createdAt: "2024-01-07T00:00:00.000Z" 
  },
  { 
    id: "p8", 
    name: "Minimalist Coffee Table", 
    slug: "minimal-coffee-table", 
    price: 12000, 
    description: "A sleek, minimalist coffee table designed for modern living spaces.",
    stock: 20, 
    categoryId: "cat_tables",
    category: { name: "Elegant Dining & Coffee Tables", slug: "tables" }, 
    images: ["https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?q=80&w=800"], 
    tags: ["living", "table", "minimalist", "modern"],
    reviews: [],
    _count: { reviews: 25 }, 
    isActive: true, 
    createdAt: "2024-01-08T00:00:00.000Z" 
  },
  { 
    id: "p9", 
    name: "Leather 3-Seater Sofa", 
    slug: "leather-sofa", 
    price: 58000, 
    description: "Premium leather 3-seater sofa offering unparalleled comfort and durability.",
    stock: 0, 
    categoryId: "cat_sofas",
    category: { name: "Luxury Sofa Sets", slug: "sofas" }, 
    images: ["https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?q=80&w=800"], 
    tags: ["living", "sofa", "leather", "luxury"],
    reviews: [],
    _count: { reviews: 6 }, 
    isActive: true, 
    createdAt: "2024-01-09T00:00:00.000Z" 
  },
  { 
    id: "p10", 
    name: "Wingback Accent Chair", 
    slug: "wingback-chair", 
    price: 22000, 
    description: "A statement wingback chair that acts as the perfect accent piece for any room.",
    stock: 7, 
    categoryId: "cat_chairs",
    category: { name: "Designer Chairs", slug: "chairs" }, 
    images: ["https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800"], 
    tags: ["seating", "accent", "classic", "bedroom"],
    reviews: [],
    _count: { reviews: 14 }, 
    isActive: true, 
    createdAt: "2024-01-10T00:00:00.000Z" 
  },
  { 
    id: "p11", 
    name: "Modern TV Unit", 
    slug: "modern-tv-unit", 
    price: 35000, 
    description: "Contemporary style solid wood TV unit complete with organized storage compartments.",
    stock: 6, 
    categoryId: "cat_media",
    category: { name: "Media & TV Consoles", slug: "media" }, 
    images: ["https://images.unsplash.com/photo-1594620302200-9a762244a156?q=80&w=800"], 
    tags: ["entertainment", "living", "storage", "modern"],
    reviews: [],
    _count: { reviews: 9 }, 
    isActive: true, 
    createdAt: "2024-01-11T00:00:00.000Z" 
  },
  { 
    id: "p12", 
    name: "Solid Wood Study Desk", 
    slug: "study-desk", 
    price: 15500, 
    description: "Classic solid wood study desk intended for focused reading or writing.",
    stock: 11, 
    categoryId: "cat_executive",
    category: { name: "Executive & Occasional Seating", slug: "executive" }, 
    images: ["https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?q=80&w=800"], 
    tags: ["office", "table", "wood", "study"],
    reviews: [],
    _count: { reviews: 30 }, 
    isActive: true, 
    createdAt: "2024-01-12T00:00:00.000Z" 
  },
];
